<?php

namespace Database\Seeders;

use App\Enums\EventStatus;
use App\Enums\EventType;
use App\Enums\VenueType;
use App\Models\Event;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class EventSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $organizer = User::first() ?? User::factory()->create();
        $now = Carbon::now();
        $defaultImg = 'https://res.cloudinary.com/dybgsw0ej/image/upload/v1756623487/5_s618dl.jpg';

        $events = [
            // Past events (11 events)
            [
                'name' => 'Urban Gardening 101',
                'description' => 'Learn how to grow your own vegetables in small urban spaces.',
                'start_time' => $now->copy()->subDays(25)->setHour(17),
                'end_time' => $now->copy()->subDays(25)->setHour(19),
                'status' => EventStatus::COMPLETED,
                'type' => EventType::SKILL_SHARING,
                'venue_type' => VenueType::ONLINE,
                'platform' => 'Zoom',
                'location' => null,
            ],
            [
                'name' => 'Sustainable Cooking Workshop',
                'description' => 'Hands-on session using locally-sourced, eco-friendly ingredients.',
                'start_time' => $now->copy()->subDays(22)->setHour(15),
                'end_time' => $now->copy()->subDays(22)->setHour(18),
                'status' => EventStatus::COMPLETED,
                'type' => EventType::SKILL_SHARING,
                'venue_type' => VenueType::OFFLINE,
                'platform' => null,
                'location' => 'Green Kitchen Studio, Yangon',
            ],
            [
                'name' => 'Food Waste Reduction Talk',
                'description' => 'Learn practical ways to reduce food waste at home.',
                'start_time' => $now->copy()->subDays(20)->setHour(18),
                'end_time' => $now->copy()->subDays(20)->setHour(20),
                'status' => EventStatus::COMPLETED,
                'type' => EventType::SKILL_SHARING,
                'venue_type' => VenueType::ONLINE,
                'platform' => 'Google Meet',
                'location' => null,
            ],
            [
                'name' => 'Farm-to-Table Cooking Class',
                'description' => 'Cook meals directly from fresh farm ingredients.',
                'start_time' => $now->copy()->subDays(18)->setHour(14),
                'end_time' => $now->copy()->subDays(18)->setHour(17),
                'status' => EventStatus::COMPLETED,
                'type' => EventType::SKILL_SHARING,
                'venue_type' => VenueType::OFFLINE,
                'platform' => null,
                'location' => 'Yangon Culinary Center',
            ],
            [
                'name' => 'Zero-Waste Meal Prep',
                'description' => 'Learn to plan meals without generating waste.',
                'start_time' => $now->copy()->subDays(15)->setHour(16),
                'end_time' => $now->copy()->subDays(15)->setHour(18),
                'status' => EventStatus::COMPLETED,
                'type' => EventType::SKILL_SHARING,
                'venue_type' => VenueType::ONLINE,
                'platform' => 'Discord',
                'location' => null,
            ],
            [
                'name' => 'Local Farmers Meetup',
                'description' => 'Connect with local farmers and food artisans.',
                'start_time' => $now->copy()->subDays(12)->setHour(17),
                'end_time' => $now->copy()->subDays(12)->setHour(20),
                'status' => EventStatus::COMPLETED,
                'type' => EventType::GATHERING,
                'venue_type' => VenueType::OFFLINE,
                'platform' => null,
                'location' => 'Yangon Community Garden',
            ],
            [
                'name' => 'Sustainable Food Expo',
                'description' => 'Explore eco-friendly food products and practices.',
                'start_time' => $now->copy()->subDays(10)->setHour(10),
                'end_time' => $now->copy()->subDays(10)->setHour(18),
                'status' => EventStatus::COMPLETED,
                'type' => EventType::GATHERING,
                'venue_type' => VenueType::OFFLINE,
                'platform' => null,
                'location' => 'Yangon Exhibition Center',
            ],
            [
                'name' => 'Cooking with Foraged Ingredients',
                'description' => 'Learn to identify and cook with edible local plants.',
                'start_time' => $now->copy()->subDays(8)->setHour(13),
                'end_time' => $now->copy()->subDays(8)->setHour(16),
                'status' => EventStatus::COMPLETED,
                'type' => EventType::GATHERING,
                'venue_type' => VenueType::OFFLINE,
                'platform' => null,
                'location' => 'Yangon Botanical Garden',
            ],
            [
                'name' => 'Fermentation Basics',
                'description' => 'Hands-on session making fermented foods like kimchi and yogurt.',
                'start_time' => $now->copy()->subDays(6)->setHour(14),
                'end_time' => $now->copy()->subDays(6)->setHour(17),
                'status' => EventStatus::COMPLETED,
                'type' => EventType::SKILL_SHARING,
                'venue_type' => VenueType::OFFLINE,
                'platform' => null,
                'location' => 'Yangon Culinary Lab',
            ],
            [
                'name' => 'Seasonal Cooking Techniques',
                'description' => 'Learn to cook using seasonal ingredients to reduce waste.',
                'start_time' => $now->copy()->subDays(4)->setHour(15),
                'end_time' => $now->copy()->subDays(4)->setHour(18),
                'status' => EventStatus::COMPLETED,
                'type' => EventType::SKILL_SHARING,
                'venue_type' => VenueType::ONLINE,
                'platform' => 'Discord',
                'location' => null,
            ],
            [
                'name' => 'Eco-Friendly Baking',
                'description' => 'Techniques for baking with minimal environmental impact.',
                'start_time' => $now->copy()->subDays(2)->setHour(14),
                'end_time' => $now->copy()->subDays(2)->setHour(17),
                'status' => EventStatus::COMPLETED,
                'type' => EventType::SKILL_SHARING,
                'venue_type' => VenueType::OFFLINE,
                'platform' => null,
                'location' => 'Yangon Bakery Studio',
            ],

            // Upcoming events (11 events)
            [
                'name' => 'Eco-Friendly Catering Meetup',
                'description' => 'Networking for chefs and caterers using sustainable methods.',
                'start_time' => $now->copy()->addDays(2)->setHour(15),
                'end_time' => $now->copy()->addDays(2)->setHour(18),
                'status' => EventStatus::SCHEDULED,
                'type' => EventType::GATHERING,
                'venue_type' => VenueType::OFFLINE,
                'platform' => null,
                'location' => 'Yangon Culinary Hub',
            ],
            [
                'name' => 'Community Clean-Up Drive',
                'description' => 'Volunteer to clean local parks and promote sustainability.',
                'start_time' => $now->copy()->addDays(4)->setHour(8),
                'end_time' => $now->copy()->addDays(4)->setHour(12),
                'status' => EventStatus::SCHEDULED,
                'type' => EventType::GATHERING,
                'venue_type' => VenueType::OFFLINE,
                'platform' => null,
                'location' => 'Inya Lake Park, Yangon',
            ],
            [
                'name' => 'Farmers Market Social',
                'description' => 'Casual gathering at a local farmers market to promote sustainable products.',
                'start_time' => $now->copy()->addDays(6)->setHour(9),
                'end_time' => $now->copy()->addDays(6)->setHour(12),
                'status' => EventStatus::SCHEDULED,
                'type' => EventType::GATHERING,
                'venue_type' => VenueType::OFFLINE,
                'platform' => null,
                'location' => 'Downtown Yangon Market',
            ],
            [
                'name' => 'Eco-Chef Challenge',
                'description' => 'Compete using sustainable cooking methods and ingredients.',
                'start_time' => $now->copy()->addDays(8)->setHour(13),
                'end_time' => $now->copy()->addDays(8)->setHour(17),
                'status' => EventStatus::SCHEDULED,
                'type' => EventType::GATHERING,
                'venue_type' => VenueType::OFFLINE,
                'platform' => null,
                'location' => 'Yangon Culinary Arena',
            ],
            [
                'name' => 'Food Sustainability Panel',
                'description' => 'Experts discuss sustainable food practices for homes and restaurants.',
                'start_time' => $now->copy()->addDays(10)->setHour(16),
                'end_time' => $now->copy()->addDays(10)->setHour(18),
                'status' => EventStatus::SCHEDULED,
                'type' => EventType::SKILL_SHARING,
                'venue_type' => VenueType::ONLINE,
                'platform' => 'Zoom',
                'location' => null,
            ],
            [
                'name' => 'Community Compost Workshop',
                'description' => 'Learn how to compost kitchen waste to enrich community gardens.',
                'start_time' => $now->copy()->addDays(12)->setHour(10),
                'end_time' => $now->copy()->addDays(12)->setHour(13),
                'status' => EventStatus::SCHEDULED,
                'type' => EventType::SKILL_SHARING,
                'venue_type' => VenueType::OFFLINE,
                'platform' => null,
                'location' => 'Yangon Community Garden',
            ],
            [
                'name' => 'Herbal Cooking Workshop',
                'description' => 'Discover how to use herbs from your garden in everyday cooking.',
                'start_time' => $now->copy()->addDays(15)->setHour(15),
                'end_time' => $now->copy()->addDays(15)->setHour(17),
                'status' => EventStatus::SCHEDULED,
                'type' => EventType::SKILL_SHARING,
                'venue_type' => VenueType::ONLINE,
                'platform' => 'Zoom',
                'location' => null,
            ],
            [
                'name' => 'Composting for Beginners',
                'description' => 'Learn the basics of composting and reducing household waste.',
                'start_time' => $now->copy()->addDays(18)->setHour(16),
                'end_time' => $now->copy()->addDays(18)->setHour(18),
                'status' => EventStatus::SCHEDULED,
                'type' => EventType::SKILL_SHARING,
                'venue_type' => VenueType::ONLINE,
                'platform' => 'Google Meet',
                'location' => null,
            ],
            [
                'name' => 'Plant-Based Meal Prep',
                'description' => 'Learn to plan nutritious plant-based meals efficiently.',
                'start_time' => $now->copy()->addDays(20)->setHour(16),
                'end_time' => $now->copy()->addDays(20)->setHour(19),
                'status' => EventStatus::SCHEDULED,
                'type' => EventType::SKILL_SHARING,
                'venue_type' => VenueType::ONLINE,
                'platform' => 'Zoom',
                'location' => null,
            ],
            [
                'name' => 'Organic Spice Blending',
                'description' => 'Create your own organic spice blends for sustainable cooking.',
                'start_time' => $now->copy()->addDays(22)->setHour(14),
                'end_time' => $now->copy()->addDays(22)->setHour(17),
                'status' => EventStatus::SCHEDULED,
                'type' => EventType::SKILL_SHARING,
                'venue_type' => VenueType::OFFLINE,
                'platform' => null,
                'location' => 'Yangon Spice Market',
            ],
            [
                'name' => 'Future of Sustainable Food',
                'description' => 'Panel discussion on emerging trends in sustainable food systems.',
                'start_time' => $now->copy()->addDays(25)->setHour(19),
                'end_time' => $now->copy()->addDays(25)->setHour(21),
                'status' => EventStatus::SCHEDULED,
                'type' => EventType::SKILL_SHARING,
                'venue_type' => VenueType::ONLINE,
                'platform' => 'Zoom',
                'location' => null,
            ],

            // Additional upcoming gatherings for better display
            [
                'name' => 'Sustainable Food Network Meetup',
                'description' => 'Connect with like-minded individuals passionate about sustainable food.',
                'start_time' => $now->copy()->addDays(28)->setHour(18),
                'end_time' => $now->copy()->addDays(28)->setHour(21),
                'status' => EventStatus::SCHEDULED,
                'type' => EventType::GATHERING,
                'venue_type' => VenueType::OFFLINE,
                'platform' => null,
                'location' => 'Yangon Community Center',
            ],
            [
                'name' => 'Green Living Showcase',
                'description' => 'Explore innovative sustainable living solutions and eco-friendly products.',
                'start_time' => $now->copy()->addDays(30)->setHour(10),
                'end_time' => $now->copy()->addDays(30)->setHour(17),
                'status' => EventStatus::SCHEDULED,
                'type' => EventType::GATHERING,
                'venue_type' => VenueType::OFFLINE,
                'platform' => null,
                'location' => 'Yangon Convention Center',
            ],
            [
                'name' => 'Community Garden Opening',
                'description' => 'Grand opening of our new community garden with food tastings and tours.',
                'start_time' => $now->copy()->addDays(32)->setHour(14),
                'end_time' => $now->copy()->addDays(32)->setHour(18),
                'status' => EventStatus::SCHEDULED,
                'type' => EventType::GATHERING,
                'venue_type' => VenueType::OFFLINE,
                'platform' => null,
                'location' => 'New Community Garden, Yangon',
            ],
            [
                'name' => 'Local Artisan Food Fair',
                'description' => 'Sample and purchase handcrafted foods from local artisans.',
                'start_time' => $now->copy()->addDays(35)->setHour(11),
                'end_time' => $now->copy()->addDays(35)->setHour(16),
                'status' => EventStatus::SCHEDULED,
                'type' => EventType::GATHERING,
                'venue_type' => VenueType::OFFLINE,
                'platform' => null,
                'location' => 'Central Market Square, Yangon',
            ],
            [
                'name' => 'Sustainable Cooking Club Meetup',
                'description' => 'Monthly gathering for cooking enthusiasts focused on sustainability.',
                'start_time' => $now->copy()->addDays(37)->setHour(17),
                'end_time' => $now->copy()->addDays(37)->setHour(20),
                'status' => EventStatus::SCHEDULED,
                'type' => EventType::GATHERING,
                'venue_type' => VenueType::OFFLINE,
                'platform' => null,
                'location' => 'Yangon Cooking Studio',
            ],
            [
                'name' => 'Virtual Sustainable Food Forum',
                'description' => 'Online community discussion about sustainable food practices worldwide.',
                'start_time' => $now->copy()->addDays(40)->setHour(19),
                'end_time' => $now->copy()->addDays(40)->setHour(21),
                'status' => EventStatus::SCHEDULED,
                'type' => EventType::GATHERING,
                'venue_type' => VenueType::ONLINE,
                'platform' => 'Discord',
                'location' => null,
            ],
            [
                'name' => 'Farm Visit & Harvest Festival',
                'description' => 'Visit local organic farms and participate in the harvest celebration.',
                'start_time' => $now->copy()->addDays(42)->setHour(9),
                'end_time' => $now->copy()->addDays(42)->setHour(15),
                'status' => EventStatus::SCHEDULED,
                'type' => EventType::GATHERING,
                'venue_type' => VenueType::OFFLINE,
                'platform' => null,
                'location' => 'Organic Farms, Outskirts of Yangon',
            ],
            [
                'name' => 'Food Waste Warriors Meetup',
                'description' => 'Join the movement to reduce food waste in our community.',
                'start_time' => $now->copy()->addDays(45)->setHour(16),
                'end_time' => $now->copy()->addDays(45)->setHour(19),
                'status' => EventStatus::SCHEDULED,
                'type' => EventType::GATHERING,
                'venue_type' => VenueType::OFFLINE,
                'platform' => null,
                'location' => 'Environmental Center, Yangon',
            ],
            [
                'name' => 'Sustainable Food Innovation Summit',
                'description' => 'Showcase of cutting-edge sustainable food technologies and innovations.',
                'start_time' => $now->copy()->addDays(48)->setHour(9),
                'end_time' => $now->copy()->addDays(48)->setHour(17),
                'status' => EventStatus::SCHEDULED,
                'type' => EventType::GATHERING,
                'venue_type' => VenueType::OFFLINE,
                'platform' => null,
                'location' => 'Yangon Tech Hub',
            ],
            [
                'name' => 'Monthly Food Sustainability Circle',
                'description' => 'Regular community circle to share sustainable food practices and experiences.',
                'start_time' => $now->copy()->addDays(50)->setHour(18),
                'end_time' => $now->copy()->addDays(50)->setHour(20),
                'status' => EventStatus::SCHEDULED,
                'type' => EventType::GATHERING,
                'venue_type' => VenueType::ONLINE,
                'platform' => 'Zoom',
                'location' => null,
            ],
        ];

        foreach ($events as $event) {
            Event::create(array_merge(
                $event,
                [
                    'id' => (string) Str::uuid(),
                    'organizer_id' => $organizer->id,
                    'image_url' => $defaultImg,
                ]
            ));
        }
    }
}
