<?php

namespace Database\Seeders;

use App\Models\Ingredient;
use Illuminate\Database\Seeder;

class IngredientsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $ingredients = [
            ['description' => '1 lb boneless, skinless chicken breast'],
            ['description' => '1 lb pasta (penne, fusilli, or spaghetti)'],
            ['description' => '2 large fresh ripe tomatoes, diced'],
            ['description' => '1 medium yellow onion, diced'],
            ['description' => '3 cloves fresh garlic, minced'],
            ['description' => '2 tbsp extra virgin olive oil'],
            ['description' => '1/4 cup fresh basil leaves'],
            ['description' => '8 oz fresh mozzarella cheese, cubed'],
            ['description' => '1 tsp sea salt'],
            ['description' => '1/2 tsp freshly ground black pepper'],
            ['description' => '1 tsp sweet paprika'],
            ['description' => '2 large bell peppers, mixed colors, sliced'],
            ['description' => '3 medium carrots, sliced'],
            ['description' => '1 head fresh broccoli, cut into florets'],
            ['description' => '8 oz button mushrooms, sliced'],
            ['description' => '2 inch piece fresh ginger root, minced'],
            ['description' => '3 tbsp light soy sauce'],
            ['description' => '2 cups long grain white rice'],
            ['description' => '1 lb ground beef (80/20)'],
            ['description' => '4 large russet potatoes, sliced'],
            ['description' => '2 cups whole milk'],
            ['description' => '2 cups shredded cheddar cheese'],
            ['description' => '4 tbsp unsalted butter'],
            ['description' => '4 cups baby spinach leaves'],
            ['description' => '2 fresh lemons, juiced'],
            ['description' => '1 can (14 oz) coconut milk'],
            ['description' => '2-3 fresh Thai chilies, minced'],
            ['description' => '1 tsp ground cumin'],
            ['description' => '1/4 cup fresh parsley, chopped'],
            ['description' => '2 cups all-purpose flour'],
            ['description' => '4 large eggs'],
            ['description' => '2 tsp baking powder'],
            ['description' => '1 cup granulated white sugar'],
            ['description' => '1 cup quinoa, uncooked'],
            ['description' => '1/2 cup crumbled feta cheese'],
            ['description' => '4 salmon fillets (6 oz each)'],
            ['description' => '1 lb fresh asparagus spears'],
            ['description' => '1 cup semi-sweet chocolate chips'],
            ['description' => '1 cup packed light brown sugar'],
            ['description' => '2 tsp pure vanilla extract'],
            ['description' => '1 tsp baking soda'],
            ['description' => '1 lb white fish fillets (cod or halibut)'],
            ['description' => '2 fresh limes, juiced'],
            ['description' => '1 small head fresh cabbage, shredded'],
            ['description' => '1/2 cup sour cream'],
            ['description' => '8 corn or flour tortillas'],
            ['description' => '1/4 cup fresh cilantro, chopped'],
            ['description' => '8 oz rice noodles or egg noodles'],
            ['description' => '3 green onions, sliced'],
            ['description' => '1 English cucumber, diced'],
            ['description' => '1/2 cup kalamata olives, pitted'],
            ['description' => '1 tbsp dried oregano'],
            ['description' => '3 ripe bananas, mashed'],
            ['description' => '1 cup dried lentils'],
            ['description' => '4 cups vegetable broth'],
            ['description' => '1 head romaine lettuce, chopped'],
            ['description' => '1/2 cup grated Parmesan cheese'],
            ['description' => '1/4 cup mayonnaise'],
            ['description' => '1 cup seasoned croutons'],
            ['description' => '2 Granny Smith apples, sliced'],
            ['description' => '1 tsp ground cinnamon'],
            ['description' => '1 lb large shrimp, peeled and deveined'],
            ['description' => '1/2 cup dry white wine'],
            ['description' => '2 ripe avocados, diced'],
            ['description' => '1 small red onion, finely diced'],
            ['description' => '1-2 jalapeño peppers, seeded and minced'],
            ['description' => '1 cup sweet corn kernels (fresh or frozen)'],
            ['description' => '1 can (15 oz) black beans, drained and rinsed'],
            ['description' => '1 cup heavy whipping cream'],
            ['description' => '4 bone-in chicken thighs'],
            ['description' => '2 sprigs fresh rosemary'],
            ['description' => '1 tbsp fresh thyme leaves'],
            ['description' => '2 large orange sweet potatoes, cubed'],
            ['description' => '2 medium zucchini, sliced'],
            ['description' => '1 large eggplant, cubed'],
            ['description' => '1/4 cup toasted pine nuts'],
            ['description' => '1/2 cup oil-packed sun-dried tomatoes, chopped'],
            ['description' => '1 cup fresh ricotta cheese'],
            ['description' => '3 tbsp raw honey'],
            ['description' => '2 tbsp aged balsamic vinegar'],
            ['description' => '2 lbs pork tenderloin'],
            ['description' => '1 lb ground turkey (93/7)'],
            ['description' => '1/2 cup chopped pecans'],
            ['description' => '1/3 cup dried cranberries'],
            ['description' => '4 oz soft goat cheese'],
            ['description' => '2 cups fresh arugula leaves'],
            ['description' => '2 tbsp brined capers'],
            ['description' => '4 oil-packed anchovy fillets'],
            ['description' => '1 tbsp Dijon mustard'],
            ['description' => '1 tbsp Worcestershire sauce'],
            ['description' => '2 tbsp toasted sesame oil'],
            ['description' => '2 tbsp rice wine vinegar'],
            ['description' => '1/2 cup natural peanut butter'],
            ['description' => '3 tbsp virgin coconut oil'],
            ['description' => '1/2 cup sliced almonds'],
            ['description' => '1/2 cup chopped walnuts'],
            ['description' => '1 cup fresh blueberries'],
            ['description' => '1 cup fresh strawberries, sliced'],
            ['description' => '1 cup plain Greek yogurt'],
            ['description' => '1 cup rolled oats'],
            ['description' => '2 tbsp chia seeds'],
            ['description' => '1/4 cup pure maple syrup'],
            ['description' => '1/2 tsp ground cardamom'],
            ['description' => '1 tsp ground turmeric'],
            ['description' => '2 tsp garam masala spice blend'],
            ['description' => '1/2 cup dry red wine'],
            ['description' => '3 dried bay leaves'],
            ['description' => '1 large fresh fennel bulb, sliced'],
            ['description' => '2 leeks, white and light green parts only, sliced'],
        ];

        foreach ($ingredients as $ingredient) {
            Ingredient::create($ingredient);
        }
    }
}
