name: food-fusion

services:
    app:
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
        container_name: food-fusion-app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        depends_on:
            - mysql
        environment:
            - DB_HOST=mysql
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=root
            - DB_PASSWORD=${DB_PASSWORD}

    nginx:
        image: nginx:latest
        container_name: food-fusion-nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    mysql:
        image: mysql:8.0
        container_name: food-fusion-mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: food-fusion-phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD: ${DB_PASSWORD}
        ports:
            - "8080:80"
        depends_on:
            - mysql
volumes:
    db_data:
        driver: local
